### ISSUE TITLE
Incidencias pierden al operador

### ISSUE THREAD

**Issue by albarro** [Arquisoft/InciDashboard_e1a#2]
Las incidencias parecen perder el operador pasado un tiempo, en el IncidenceTest esta marcado donde deja de tenerlo

**Comment by angelpuerta** [comment]
La tabla de operadores no elimina los operadores pese a que la propiedad spring.jpa.hibernate.ddl-auto está como create-drop

**Comment by albarro** [comment]
Esto se ha solucionado con el cambio de base
